### 1. Imports

In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns
import json
import unidecode
from matplotlib import pyplot as plt
import ast
from flaml import AutoML
from sklearn.cluster import KMeans
import ast

c:\Users\rlope\anaconda3\envs\hc_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-12-11 11:13:52,948	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2025-12-11 11:13:53,223	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

In [2]:
# Evitar printar warnings
import warnings 
warnings.filterwarnings("ignore")

### 2. Load data and Overview

In [3]:
train_df = pd.read_csv('../data/train_split.csv')
test_df = pd.read_csv('../data/test_split.csv') 

# Train & test dataframes  shape
print(train_df.shape, test_df.shape)

(110000, 70) (39867, 70)

In [4]:
df_train_embeddings = pd.read_csv('../data/hc_proyecto_train_data_embeddings.csv')
df_test_embeddings = pd.read_csv('../data/hc_proyecto_test_data_embeddings.csv')

In [5]:
def parse_numpy_str(s):
    # 1. Quitamos corchetes
    s = s.strip("[]")
    # 2. Reemplazamos comas por espacios (por si acaso vienen separados por comas)
    s = s.replace(',', ' ')
    # 3. Convertimos
    arr = np.fromstring(s, sep=' ').tolist()
    return arr

# 2. Aplicarlo a tu DataFrame
df_train_embeddings['descripcion_embeddings'] = df_train_embeddings['descripcion_embeddings'].apply(parse_numpy_str)
df_test_embeddings['descripcion_embeddings'] = df_test_embeddings['descripcion_embeddings'].apply(parse_numpy_str)

In [6]:
embedding_dim = len(df_train_embeddings.iloc[0]["descripcion_embeddings"])
# Convertir la columna de embeddings en una matriz 2D
emb_matrix = np.vstack(df_train_embeddings["descripcion_embeddings"].values)
# Crear un nuevo dataframe de columnas emb_0, emb_1, ...
emb_df = pd.DataFrame(
    emb_matrix,
    columns=[f"emb_{i}" for i in range(embedding_dim)]
)

embedding_dim_2 = len(df_test_embeddings.iloc[0]["descripcion_embeddings"])
# Convertir la columna de embeddings en una matriz 2D
emb_matrix_2 = np.vstack(df_test_embeddings["descripcion_embeddings"].values)
# Crear un nuevo dataframe de columnas emb_0, emb_1, ...
emb_df_2 = pd.DataFrame(
    emb_matrix_2,
    columns=[f"emb_{i}" for i in range(embedding_dim_2)]
)


train_df = pd.concat([train_df, emb_df],axis=1)
test_df = pd.concat([test_df, emb_df_2],axis=1)

In [7]:
# First overview of train dataframe features/target info
train_df.info()
# # Look at top 5 rows
train_df.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110000 entries, 0 to 109999
Columns: 326 entries, id to emb_255
dtypes: bool(1), float64(276), int64(3), object(46)
memory usage: 272.9+ MB

,id,ciudad,estado,estado_propiedad,dormitorios,banos,precio,anio_construccion,codigo_postal,longitud,...,emb_246,emb_247,emb_248,emb_249,emb_250,emb_251,emb_252,emb_253,emb_254,emb_255
0,1,Lakeland,FL,FOR_SALE,3.0,2.0,119900.0,NaN,33810,-81.97661,...,0.055814,0.083686,-0.002043,0.069716,0.094002,-0.034311,-0.043107,0.045225,0.055779,-0.000019
1,2,Pompano Beach,FL,FOR_SALE,3.0,2.0,290000.0,NaN,33067,-80.24621,...,0.054837,0.142771,-0.021663,0.012974,0.083022,-0.025964,-0.021053,-0.034879,0.058153,0.063659
2,3,Jacksonville,FL,FOR_SALE,3.0,3.0,599000.0,NaN,32205,-81.71293,...,0.022639,0.138726,-0.025745,0.000391,0.048933,-0.099128,0.054381,0.026659,-0.045843,0.021626

In [8]:
# Elimino las columnas id de ambos datasets
train_df.drop(columns=['id'], inplace=True)

test_ids_list = test_df['id'].values # Extraemos para luego usarlo en el submission 
test_df.drop(columns=['id'], inplace=True)

In [9]:
len(test_ids_list)

39867

In [10]:
# Train & test dataframes  shape
print(train_df.shape, test_df.shape)

(110000, 325) (39867, 325)

In [11]:
# Determino intersección en columnas entre train y test
common_cols = train_df.columns.intersection(test_df.columns)
len(common_cols)

325

In [12]:
# Cargo las feature importances de un entrenamiento previo de autogluon: 

df_feature_importances = pd.read_csv('../data/autogluon_submission5_importances.csv').sort_values(by='importance',ascending=False)
df_feature_importances

,Unnamed: 0,importance,stddev,p_value,n,p99_high,p99_low
51,descripcion,2.227178e-01,8.809284e-03,2.931019e-07,5,2.408562e-01,2.045794e-01
50,ciudad,1.921730e-01,2.428680e-03,3.060559e-09,5,1.971737e-01,1.871723e-01
49,valor_area_habitable,1.807573e-01,2.696772e-03,5.943558e-09,5,1.863100e-01,1.752046e-01
48,latitud,1.516501e-01,4.131508e-03,6.604125e-08,5,1.601569e-01,1.431433e-01
47,tipo_vivienda,1.157187e-01,1.922989e-03,9.147754e-09,5,1.196782e-01,1.117592e-01
46,longitud,1.113356e-01,4.575521e-03,3.415305e-07,5,1.207567e-01,1.019146e-01
45,interior_completo,1.068882e-01,1.791449e-03,9.464939e-09,5,1.105768e-01,1.031995e-01
44,area_habitable,1.043969e-01,2.033041e-03,1.725025e-08,5,1.085830e-01,1.002109e-01
43,tamano_lote,8.498194e-02,3.058599e-03,2.010088e-07,5,9.127964e-02,7.868425e-02
42,construccion,7.965611e-02,5.954555e-04,3.746881e-10,5,8.088216e-02,7.843006e-02
41,banos,6.325923e-02,2.199543e-03,1.751118e-07,5,6.778812e-02,5.873034e-02
40,interior,4.303771e-02,1.841508e-03,4.012546e-07,5,4.682940e-02,3.924602e-02
39,servicios,4.246963e-02,1.763464e-03,3.559070e-07,5,4.610062e-02,3.883863e-02
38,detalles_comunidad,4.167316e-02,1.707539e-03,3.374944e-07,5,4.518901e-02,3.815732e-02
37,elegibilidad_recorrido,4.001008e-02,2.020797e-03,7.782491e-07,5,4.417093e-02,3.584923e-02
36,dormitorios,2.044412e-02,3.625268e-04,1.186003e-08,5,2.119057e-02,1.969767e-02
35,conteo_fotos,2.023980e-02,9.840615e-04,6.684632e-07,5,2.226600e-02,1.821361e-02
34,dimension_tipo_publicacion,2.023231e-02,2.751756e-03,4.006847e-05,5,2.589822e-02,1.456641e-02
33,puntajes_movilidad,1.981384e-02,8.861188e-04,4.787595e-07,5,2.163837e-02,1.798931e-02
32,tasa_impuesto_propiedad,1.633115e-02,5.377488e-04,1.408655e-07,5,1.743838e-02,1.522391e-02
31,valor_area_lote,1.018412e-02,5.839932e-04,1.291863e-06,5,1.138657e-02,8.981671e-03
30,codigo_postal,9.169895e-03,2.768153e-04,9.953062e-08,5,9.739861e-03,8.599928e-03
29,dias_en_portal,5.373717e-03,2.295689e-04,3.987296e-07,5,5.846402e-03,4.901031e-03
28,ciudades_cercanas,3.951564e-03,3.347397e-04,6.120546e-06,5,4.640798e-03,3.262330e-03
27,dias_en_portal_detalle,3.248626e-03,3.107769e-04,9.928790e-06,5,3.888520e-03,2.608732e-03
26,unidades_area_lote,2.979842e-03,3.080023e-04,1.350401e-05,5,3.614023e-03,2.345661e-03
25,codigos_postales_cercanos,2.955698e-03,1.878182e-04,1.946064e-06,5,3.342418e-03,2.568978e-03
24,escuelas,2.935219e-03,1.630775e-04,1.138701e-06,5,3.270998e-03,2.599440e-03
23,anio_construccion,2.067375e-03,3.259854e-04,7.178522e-05,5,2.738583e-03,1.396166e-03
22,nombre_corredor,1.390501e-03,1.386749e-04,1.171521e-05,5,1.676034e-03,1.104967e-03
21,zona_horaria,1.379674e-03,2.015830e-04,5.316555e-05,5,1.794736e-03,9.646112e-04
20,vecindarios_cercanos,1.110207e-03,3.147674e-04,6.988015e-04,5,1.758317e-03,4.620965e-04
19,es_constructor_premier,7.609127e-04,3.055936e-04,2.548883e-03,5,1.390134e-03,1.316912e-04
18,condado,6.445309e-04,2.006781e-04,9.955364e-04,5,1.057730e-03,2.313319e-04
17,riesgos_climaticos,3.041722e-04,4.342766e-05,4.853513e-05,5,3.935904e-04,2.147541e-04
16,resumen,2.161199e-04,1.169978e-04,7.244043e-03,5,4.570201e-04,-2.478027e-05
15,url_tour_virtual_tercero_aprobado,9.110984e-05,4.282693e-05,4.462416e-03,5,1.792911e-04,2.928605e-06
14,direccion_no_divulgada,6.113372e-05,5.030967e-05,2.657140e-02,5,1.647220e-04,-4.245458e-05
13,tiene_video_publico,2.932204e-05,1.914767e-05,1.333817e-02,5,6.874735e-05,-1.010327e-05
12,dimension_tipo_hdp,2.733745e-05,3.441812e-05,7.518728e-02,5,9.820483e-05,-4.352994e-05
11,unidades_area_habitable,2.291280e-05,2.631770e-05,6.170680e-02,5,7.710131e-05,-3.127571e-05
10,fecha_venta_texto,1.133390e-05,2.772383e-05,2.061817e-01,5,6.841765e-05,-4.574985e-05
9,unidades_area_habitable_corto,9.974599e-06,3.620649e-05,2.856045e-01,5,8.452426e-05,-6.457506e-05
8,auto_recorrido,7.801171e-06,2.888842e-06,1.896394e-03,5,1.374934e-05,1.853005e-06
7,es_mostrado,4.791486e-06,1.333698e-05,2.334013e-01,5,3.225251e-05,-2.266954e-05
6,ocupado_no_propietario,4.003699e-07,1.162546e-05,4.711576e-01,5,2.433736e-05,-2.353662e-05
5,geocodificacion_deficiente,2.146912e-07,6.062109e-07,2.363644e-01,5,1.462888e-06,-1.033505e-06
4,tasas_hipoteca,1.320267e-07,3.486132e-07,2.223876e-01,5,8.498261e-07,-5.857727e-07
3,oferta_inmediata_habilitada,0.000000e+00,0.000000e+00,5.000000e-01,5,0.000000e+00,0.000000e+00
2,conteo_vistas_recorrido,0.000000e+00,0.000000e+00,5.000000e-01,5,0.000000e+00,0.000000e+00
1,avaluo_vivienda,-3.097534e-07,6.900712e-07,8.138439e-01,5,1.111113e-06,-1.730620e-06
0,es_destacado,-1.915817e-06,1.209624e-06,9.880096e-01,5,5.748158e-07,-4.406450e-06

In [13]:
# Podemos observar que ya hay features numéricos con demasiados valores NULOS que podemos obviar de primeras
FEATURES2DROP = [
    "datos_residenciales_alcantarillado", 
    "datos_residenciales_fuente_agua", 
    "numero_unidad",
    "pies_cuadrados",
    "fecha_disponibilidad",
    "oferta_especial",
    "anio_construccion",
    ## Añado variables que no aportan importancia
    'es_destacado', 
    'avaluo_vivienda',
    'conteo_visitas_recorrido', 
    'oferta_inmediata_habilitada']
    
# Extraigo el precio de las variables FEATURES ya que es el target
TARGET = "precio"
FEATURES2DROP +=[TARGET]

#### 3.2. Imputación de variables numericas

In [14]:
# Quitar los registros del train que tengan NaN
train_df = train_df[~train_df['precio'].isna()]

In [15]:
# Mediana por (baños, habitaciones)
median_map_full = train_df.groupby(["banos", "dormitorios"])["area_habitable"].median()

# Mediana solo por habitaciones
median_map_rooms = train_df.groupby(["dormitorios"])["area_habitable"].median()

# Mediana solo por baños
median_map_bath = train_df.groupby(["banos"])["area_habitable"].median()

# Mediana global del train
global_median = train_df["area_habitable"].median()

def impute_area(row):
    if not pd.isna(row["area_habitable"]):
        return row["area_habitable"]

    # 1. Por (baños, habitaciones)
    key_full = (row["banos"], row["dormitorios"])
    val = median_map_full.get(key_full)
    if not pd.isna(val):
        return val

    # 2. Solo por habitaciones
    val = median_map_rooms.get(row["dormitorios"])
    if not pd.isna(val):
        return val

    # 3. Solo por baños
    val = median_map_bath.get(row["banos"])
    if not pd.isna(val):
        return val

    # 4. Mediana global del train
    return global_median


def fill_nans_with_median(train_df, test_df, feature): 
    mediana_dorm = train_df[feature].median()
    train_df[feature] = train_df[feature].fillna(mediana_dorm)
    test_df[feature] = test_df[feature].fillna(mediana_dorm)
    return train_df, test_df

def fill_nans_with_mode(train_df, test_df, feature): 
    mediana_dorm = train_df[feature].mode()[0]
    train_df[feature] = train_df[feature].fillna(mediana_dorm)
    test_df[feature] = test_df[feature].fillna(mediana_dorm)
    return train_df, test_df

In [16]:
# Variables numéricas
# Imputar NaNs tanto en train como en test
train_df, test_df = fill_nans_with_mode(train_df, test_df, 'dormitorios')
train_df, test_df = fill_nans_with_mode(train_df, test_df, 'banos')
train_df, test_df = fill_nans_with_mode(train_df, test_df, 'dias_en_portal')

train_df["area_habitable"] = train_df.apply(impute_area, axis=1)
test_df["area_habitable"] = test_df.apply(impute_area, axis=1)

# Hay casos donde el value_counts es 1 o hay discrepancias en algunas casuísticas. 
# Por lo que decido seleccionar la zona horaria por ciudad con más frecuencia de aparición. 
zona_horaria_dominante = (train_df.groupby("codigo_postal")["zona_horaria"].agg(lambda x: x.value_counts().idxmax()))
train_df['zona_horaria'] = train_df['codigo_postal'].map(zona_horaria_dominante)
test_df['zona_horaria'] = test_df['codigo_postal'].map(zona_horaria_dominante)


## Tasa de impuesto de propiedad
# Ajustarla por codigo_postal a la mediana del valor del codigo postal

cp_impuesto_dict = dict(train_df.groupby('codigo_postal')['tasa_impuesto_propiedad'].median())
train_df['tasa_impuesto_propiedad'] = train_df['tasa_impuesto_propiedad'].fillna(train_df['codigo_postal'].map(cp_impuesto_dict))
# Si se mantiene algun NaN sustituir por la mediana global
train_df['tasa_impuesto_propiedad'] = train_df['tasa_impuesto_propiedad'].fillna(train_df['tasa_impuesto_propiedad'].median())

test_df['tasa_impuesto_propiedad'] = test_df['tasa_impuesto_propiedad'].fillna(test_df['codigo_postal'].map(cp_impuesto_dict))
test_df['tasa_impuesto_propiedad'] = test_df['tasa_impuesto_propiedad'].fillna(train_df['tasa_impuesto_propiedad'].median())


# Para latitud y longitud considerar la mediana por zona
media_lat_por_cp = dict(train_df.groupby('codigo_postal')['latitud'].mean())
media_long_por_cp = dict(train_df.groupby('codigo_postal')['longitud'].mean())

train_df['latitud'] = train_df['latitud'].fillna(train_df['codigo_postal'].map(media_lat_por_cp))
train_df['longitud'] = train_df['longitud'].fillna(train_df['codigo_postal'].map(media_long_por_cp))

test_df['latitud'] = test_df['latitud'].fillna(test_df['codigo_postal'].map(media_lat_por_cp))
test_df['longitud'] = test_df['longitud'].fillna(test_df['codigo_postal'].map(media_long_por_cp))

In [17]:
# Direccion no divulgada
# La gran mayoría de los casos son False, por lo que los NaNs los sustituiremos por False
train_df['direccion_no_divulgada'] = train_df['direccion_no_divulgada'].fillna(False)
test_df['direccion_no_divulgada'] = test_df['direccion_no_divulgada'].fillna(False)

## Es constructor premier
# La gran mayoria de los casos son False, por lo que los NaNs los sustituiremos por False
train_df['es_constructor_premier'] = train_df['es_constructor_premier'].fillna(False)
test_df['es_constructor_premier'] = test_df['es_constructor_premier'].fillna(False)

## Tiene video publico 
# Solo se informan los False por lo que entendemos que los NaN son True
train_df['tiene_video_publico'] = train_df['tiene_video_publico'].fillna(True)
test_df['tiene_video_publico'] = test_df['tiene_video_publico'].fillna(True)

## url_tour_virtual_terceros
# Rellenamos los Nan con el valor con mayor frecuencia --> False
train_df['url_tour_virtual_tercero_aprobado'] = train_df['url_tour_virtual_tercero_aprobado'].fillna(False)
test_df['url_tour_virtual_tercero_aprobado'] = test_df['url_tour_virtual_tercero_aprobado'].fillna(False)

In [18]:
# Hay un negativo en dias en portal --> transformo en valor absoluto 
train_df['dias_en_portal'] = train_df['dias_en_portal'].apply(lambda x: np.abs(x))
test_df['dias_en_portal'] = test_df['dias_en_portal'].apply(lambda x: np.abs(x))

In [19]:
def transformacion_log1p_variables_right_skewed_train_test(train_df, test_df, feature): 
    train_df[feature] = train_df[feature].apply(lambda x: np.log1p(x))
    test_df[feature] = test_df[feature].apply(lambda x: np.log1p(x))
    return (train_df, test_df)

# Como dias en portal es una variable right skewed sustituyo valores que superen el limite de outliers por la mediana 
train_df, test_df = transformacion_log1p_variables_right_skewed_train_test(train_df, test_df, 'dias_en_portal')
train_df, test_df = transformacion_log1p_variables_right_skewed_train_test(train_df, test_df, 'dormitorios')
train_df, test_df = transformacion_log1p_variables_right_skewed_train_test(train_df, test_df, 'banos')
train_df, test_df = transformacion_log1p_variables_right_skewed_train_test(train_df, test_df, 'area_habitable')

In [20]:
from sklearn.model_selection import train_test_split
# Usar autogluon 
from autogluon.tabular import TabularPredictor

In [21]:
train_df.columns

Index(['ciudad', 'estado', 'estado_propiedad', 'dormitorios', 'banos',
       'precio', 'anio_construccion', 'codigo_postal', 'longitud', 'latitud',
       ...
       'emb_246', 'emb_247', 'emb_248', 'emb_249', 'emb_250', 'emb_251',
       'emb_252', 'emb_253', 'emb_254', 'emb_255'],
      dtype='object', length=325)

In [22]:

X = train_df[[f for f in train_df[[f for f in train_df.columns if f not in FEATURES2DROP + ['descripcion_embeddings', 'codigo_postal', 'conteo fotos']]] if f not in ['precio']]]
y = train_df['precio'].apply(lambda x: np.log1p(x))
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# AutoGluon espera un DataFrame completo con la columna objetivo
train_data = X_train.copy()
train_data['target'] = y_train

test_data = X_test.copy()
test_data['target'] = y_test

In [23]:
# Definir el predictor
predictor = TabularPredictor(label='target', eval_metric='mae').fit(
    train_data=train_data,
    time_limit=2500,  # tiempo máximo en segundos
    presets='medium_quality'  # opcional: hace un entrenamiento más completo
)

No path specified. Models will be saved in: "AutogluonModels\ag-20251211_101431"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.10.19
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26100
CPU Count:          12
Memory Avail:       6.19 GB / 15.93 GB (38.9%)
Disk Space Avail:   78.84 GB / 222.73 GB (35.4%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 2500s
AutoGluon will save models to "c:\Users\rlope\Documents\Master UB IA mercados financieros\repos\proyecto_hc\notebooks\AutogluonModels\ag-20251211_101431"
Train Data Rows:    87974
Train Data Columns: 313
Label Column:       target
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (19.467999741741696, 0.0, 12.8643, 1.22508)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6769.39 MB
	Train Data (Original)  Memory Usage: 651.68 MB (9.6% of available memory)
	Warning: Data size prior to feature transformation consumes 9.6% of available memory. Consider increasing memory or subsampling the data to avoid instability.
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 10 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['descripcion', 'escuelas', 'ciudades_cercanas', 'vecindarios_cercanos', 'nombre_corredor', 'servicios', 'interior', 'interior_completo', 'construccion', 'detalles_comunidad', 'puntajes_movilidad']
			CountVectorizer fit with vocabulary size = 10000
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 10000 to 561 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 4): ['estado', 'estado_propiedad', 'pais', 'fuera_del_mercado']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Unused Original Features (Count: 4): ['dimension_tipo_propiedad', 'fecha_venta', 'limite_clientes_renta', 'movilidad']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 4 | ['dimension_tipo_propiedad', 'fecha_venta', 'limite_clientes_renta', 'movilidad']
	Types of features in original data (raw dtype, special dtypes):
		('bool', [])         :   4 | ['direccion_no_divulgada', 'es_constructor_premier', 'tiene_video_publico', 'url_tour_virtual_tercero_aprobado']
		('float', [])        : 268 | ['dormitorios', 'banos', 'longitud', 'latitud', 'area_habitable', ...]
		('int', [])          :   1 | ['conteo_fotos']
		('object', [])       :  21 | ['ciudad', 'geocodificacion_deficiente', 'tipo_vivienda', 'unidades_area_lote', 'unidades_area_habitable_corto', ...]
		('object', ['text']) :  11 | ['descripcion', 'escuelas', 'ciudades_cercanas', 'vecindarios_cercanos', 'nombre_corredor', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :  16 | ['ciudad', 'geocodificacion_deficiente', 'tipo_vivienda', 'unidades_area_lote', 'fecha_venta_texto', ...]
		('category', ['text_as_category'])  :  11 | ['descripcion', 'escuelas', 'ciudades_cercanas', 'vecindarios_cercanos', 'nombre_corredor', ...]
		('float', [])                       : 268 | ['dormitorios', 'banos', 'longitud', 'latitud', 'area_habitable', ...]
		('int', [])                         :   1 | ['conteo_fotos']
		('int', ['binned', 'text_special']) : 173 | ['descripcion.char_count', 'descripcion.word_count', 'descripcion.capital_ratio', 'descripcion.lower_ratio', 'descripcion.digit_ratio', ...]
		('int', ['bool'])                   :   9 | ['unidades_area_habitable_corto', 'direccion_no_divulgada', 'es_constructor_premier', 'tiene_video_publico', 'unidades_area_habitable', ...]
		('int', ['text_ngram'])             : 428 | ['__nlp__.00', '__nlp__.10', '__nlp__.100', '__nlp__.100 somewhat', '__nlp__.100 somewhat bikeable', ...]
	316.4s = Fit runtime
	305 features in original data used to generate 906 features in processed data.
	Train Data (Processed) Memory Usage: 271.01 MB (3.6% of available memory)
Data preprocessing and feature engineering runtime = 316.93s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.02841748698479096, Train Rows: 85474, Val Rows: 2500
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 2183.07s of the 2183.07s of remaining time.
	Fitting with cpus=6, gpus=0, mem=1.5/6.1 GB

[1000]	valid_set's l1: 0.221747
[2000]	valid_set's l1: 0.214803
[3000]	valid_set's l1: 0.211373
[4000]	valid_set's l1: 0.208799
[5000]	valid_set's l1: 0.207333
[6000]	valid_set's l1: 0.206414
[7000]	valid_set's l1: 0.20545
[8000]	valid_set's l1: 0.204675
[9000]	valid_set's l1: 0.204365
[10000]	valid_set's l1: 0.203962

	-0.204	 = Validation score   (-mean_absolute_error)
	388.87s	 = Training   runtime
	0.49s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 1793.13s of the 1793.13s of remaining time.
	Fitting with cpus=6, gpus=0, mem=1.5/6.1 GB

[1000]	valid_set's l1: 0.219229
[2000]	valid_set's l1: 0.214046
[3000]	valid_set's l1: 0.21269
[4000]	valid_set's l1: 0.211712
[5000]	valid_set's l1: 0.210983
[6000]	valid_set's l1: 0.210419
[7000]	valid_set's l1: 0.210099
[8000]	valid_set's l1: 0.209919
[9000]	valid_set's l1: 0.209791
[10000]	valid_set's l1: 0.209708

	-0.2097	 = Validation score   (-mean_absolute_error)
	444.74s	 = Training   runtime
	0.65s	 = Validation runtime
Fitting model: RandomForestMSE ... Training model for up to 1346.98s of the 1346.98s of remaining time.
	Fitting with cpus=12, gpus=0, mem=0.1/6.0 GB
	Warning: Reducing model 'n_estimators' from 300 -> 93 due to low time. Expected time usage reduced from 4297.3s -> 1345.7s...
	-0.2739	 = Validation score   (-mean_absolute_error)
	570.57s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 776.18s of the 776.18s of remaining time.
	Fitting with cpus=6, gpus=0, mem=2.5/5.7 GB
	Ran out of time, early stopping on iteration 2747.
	-0.2237	 = Validation score   (-mean_absolute_error)
	776.13s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the -0.13s of remaining time.
	Ensemble Weights: {'LightGBMXT': 0.526, 'LightGBM': 0.368, 'CatBoost': 0.105}
	-0.1981	 = Validation score   (-mean_absolute_error)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 2505.03s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 1987.7 rows/s (2500 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\rlope\Documents\Master UB IA mercados financieros\repos\proyecto_hc\notebooks\AutogluonModels\ag-20251211_101431")

In [24]:
results = predictor.evaluate(test_data)
print(results)

{'mean_absolute_error': -0.1965640562214647, 'root_mean_squared_error': np.float64(-0.33317285432004773), 'mean_squared_error': -0.11100415085576774, 'r2': 0.929901836368973, 'pearsonr': 0.9645688418844147, 'median_absolute_error': -0.12919538292645516}

In [25]:
# codigo postal y conteo fotos molestan en el predict

In [26]:
y_test_predicted = predictor.predict(test_df[[f for f in train_df.columns if f not in FEATURES2DROP + ['descripcion_embeddings', 'codigo_postal', 'conteo fotos']]])

In [27]:
# Transformación inversa a escala original
final_y_pred = np.expm1(y_test_predicted)

In [28]:
len(y_test_predicted)

39867

In [29]:
len(y_test_predicted)

39867

In [30]:
submission_df = pd.DataFrame(test_ids_list)
submission_df

            0
0      110001
1      110002
2      110003
3      110004
4      110005
...       ...
39862  149863
39863  149864
39864  149865
39865  149866
39866  149867

[39867 rows x 1 columns]

In [31]:
submission_df = pd.DataFrame(test_ids_list)
submission_df['precio'] = final_y_pred
submission_df = submission_df.rename(columns={0:'id'})
submission_df.head(3)

       id        precio
0  110001  1.061097e+06
1  110002  4.094994e+05
2  110003  1.546010e+05

In [32]:
submission_df.to_csv('../data/submission9.csv',index=False)

In [ ]:
test_df.shape

(39867, 738)